name: CI/CD Pipeline - React GKE

on:
  push:
    branches: [ main ]

jobs:

  # ------------------ STAGE 1: Checkout ------------------
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  # ------------------ STAGE 2: Install ------------------
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install

  # ------------------ STAGE 3: Linting ------------------
  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

  # ------------------ STAGE 4: Security Scan ------------------
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run npm audit
        run: npm audit --audit-level=moderate || echo "Warnings ignored"

  # ------------------ STAGE 5: Unit Tests ------------------
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: security
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test -- --coverage --passWithNoTests

  # ------------------ STAGE 6: Authenticate & Build ------------------
  build:
    name: Authenticate & Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    env:
      IMAGE_TAG: ${{ github.sha }}
      PROJECT_ID: ${{ vars.GCP_PROJECT }}
      CLUSTER_NAME: ${{ vars.GKE_CLUSTER }}
      GKE_ZONE: ${{ vars.GKE_ZONE }}
      REGISTRY: ${{ vars.REGISTRY }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      ARTIFACT_REPO: ${{ vars.ARTIFACT_REPO }}
    steps:
      - uses: actions/checkout@v4
      - name: Auth & Docker Build
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker $REGISTRY
          docker build -t $REGISTRY/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME:$IMAGE_TAG .

  # ------------------ STAGE 7: Trivy Scan ------------------
  scan:
    name: Trivy Scan
    runs-on: ubuntu-latest
    needs: build
    env:
      IMAGE_TAG: ${{ github.sha }}
      PROJECT_ID: ${{ vars.GCP_PROJECT }}
      REGISTRY: ${{ vars.REGISTRY }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      ARTIFACT_REPO: ${{ vars.ARTIFACT_REPO }}
    steps:
      - name: Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  # ------------------ STAGE 8: Push Image ------------------
  push:
    name: Push Image to Artifact Registry
    runs-on: ubuntu-latest
    needs: scan
    env:
      IMAGE_TAG: ${{ github.sha }}
      PROJECT_ID: ${{ vars.GCP_PROJECT }}
      REGISTRY: ${{ vars.REGISTRY }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      ARTIFACT_REPO: ${{ vars.ARTIFACT_REPO }}
    steps:
      - uses: actions/checkout@v4
      - name: Push Image
        run: docker push $REGISTRY/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME:$IMAGE_TAG

  # ------------------ STAGE 9: Deploy to GKE ------------------
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: push
    env:
      IMAGE_TAG: ${{ github.sha }}
      PROJECT_ID: ${{ vars.GCP_PROJECT }}
      CLUSTER_NAME: ${{ vars.GKE_CLUSTER }}
      GKE_ZONE: ${{ vars.GKE_ZONE }}
      REGISTRY: ${{ vars.REGISTRY }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      ARTIFACT_REPO: ${{ vars.ARTIFACT_REPO }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ vars.GCP_PROJECT }}

      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin -q
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --zone $GKE_ZONE --project $PROJECT_ID

      - name: Deploy App
        run: |
          kubectl set image deployment/react-frontend react-frontend=$REGISTRY/$PROJECT_ID/$ARTIFACT_REPO/$IMAGE_NAME:$IMAGE_TAG || kubectl apply -f k8s/
          kubectl rollout status deployment/react-frontend
